/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus_placement_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateCompany extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCompany
     */
    public UpdateCompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCname = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtMinPer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCnameSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbCSE = new javax.swing.JCheckBox();
        cbISE = new javax.swing.JCheckBox();
        cbECE = new javax.swing.JCheckBox();
        cbMEC = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        jLabel1.setText("Company Name");

        jLabel2.setText("Seats Offered");

        jLabel3.setText("Minimum Percentage");

        txtMinPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPerActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Company Name");

        jLabel5.setText("Branch");

        cbCSE.setText("CSE");

        cbISE.setText("ISE");

        cbECE.setText("ECE");
        cbECE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbECEActionPerformed(evt);
            }
        });

        cbMEC.setText("MEC");
        cbMEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMECActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("UPDATE COMPANY DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(67, 67, 67)
                                            .addComponent(cbCSE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(cbISE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbECE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSeats)
                                        .addComponent(txtCname)
                                        .addComponent(txtMinPer)
                                        .addComponent(txtCnameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4)
                                .addComponent(cbMEC)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCnameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMinPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCSE)
                    .addComponent(cbISE)
                    .addComponent(cbECE)
                    .addComponent(cbMEC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbECEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbECEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbECEActionPerformed

    private void cbMECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMECActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus","root", "SQLpassword");
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
//            String q,sid,fn,ln,str,per,ph,em;
//            sid=txtUsn.getText();
//            fn=txtFname.getText();
//            ln=txtLname.getText();
//            str=cmbStream.getSelectedItem().toString();
//            per=txtPer.getText();
//            ph=txtPhone.getText();
//            em=txtEmail.getText();
            String q,n,s,p,q1;
            boolean cs,is,ec,me;
            n=txtCname.getText();
            s=txtSeats.getText();
            p=txtMinPer.getText();
            cs=cbCSE.isSelected();
            is=cbISE.isSelected();
            ec=cbECE.isSelected();
            me=cbMEC.isSelected();
            q="update company set cname='"+n+"',seats_offered="+s+",min_per="+p+" where cname='"+n+"' ";
            
            st.executeUpdate(q);
            q1="delete from company_profile where cname='"+n+"'";
            st.executeUpdate(q1);
            if(cs)
            {
                q1="insert into company_profile values ('"+n+"' , 'CSE')";
                st.executeUpdate(q1);
            }
            if(is)
            {
                q1="insert into company_profile values ('"+n+"' , 'ISE')";
                st.executeUpdate(q1);
            }
            if(ec)
            {
                q1="insert into company_profile values ('"+n+"' , 'ECE')";
                st.executeUpdate(q1);
            }
            if(me)
            {
                q1="insert into company_profile values ('"+n+"' , 'MEC')";
                st.executeUpdate(q1);
            }
            JOptionPane.showMessageDialog(this,"Company's deatils UPDATED !! ");
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus","root", "SQLpassword");
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String cname,search,minper,seats;
            boolean cs=false,is=false,ec=false,me=false;
            String q,temp;
            search=txtCnameSearch.getText();
            //txtFname.setText(sid);
            q="select c.cname,c.seats_offered,c.min_per,cp.branch from company c, company_profile cp where c.cname='"+search+"' and c.cname=cp.cname";
            ResultSet rs = st.executeQuery(q);
            //if(rs.first())
            int flag=0;
            while(rs.next())
            {
                flag=1;
                /*fn=rs.getString("firstname");
                ln=rs.getString("lastname");
                per=rs.getString("perc");
                str=rs.getString("stream");
                ph=rs.getString("phone");
                em=rs.getString("email");*/
                cname=rs.getString("cname");
                seats=rs.getString("seats_offered");
                minper=rs.getString("min_per");
                temp=rs.getString("branch");
                if(temp.equals("CSE"))
                    cs=true;
                if(temp.equals("ISE"))
                    is=true;
                if(temp.equals("ECE"))
                    ec=true;
                if(temp.equals("MEC"))
                    me=true;
                txtCname.setText(cname);
                txtCname.setEnabled(false);
                txtSeats.setText(seats);
                txtMinPer.setText(minper);
                
                if(cs==true)
                {
                    cbCSE.setSelected(true);
                }
                if(is==true)
                {
                    cbISE.setSelected(true);
                }
                if(ec==true)
                {
                    cbECE.setSelected(true);
                }
                if(me==true)
                {
                    cbMEC.setSelected(true);
                }
                
                
//                txtFname.setText(fn);
//                txtLname.setText(ln);
//                txtPer.setText(per);
//                cmbStream.setSelectedItem(str);
//                
//                txtPhone.setText(ph);
//                txtEmail.setText(em);
                
                
            }
            if(flag==0)
                JOptionPane.showMessageDialog(this, "No Company found with given Company Name");
        }
        catch(Exception w)
        {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtMinPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinPerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtCnameSearch.setText("");
        txtCname.setText("");
        txtSeats.setText("");
        txtMinPer.setText("");
        cbCSE.setSelected(false);
        cbISE.setSelected(false);
        cbECE.setSelected(false);
        cbMEC.setSelected(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus","root", "SQLpassword");
            Statement st=con.createStatement();
            String q,q1,cname;
            cname=txtCnameSearch.getText();
            //JOptionPane.showMessageDialog(this,sid);
            q="delete from company_profile where cname='"+cname+"'";
            st.executeUpdate(q);
            q1="delete from company where cname='"+cname+"'";
            st.executeUpdate(q1);
            JOptionPane.showMessageDialog(this,"Company Deleted !!");
        }
        catch(Exception e)
        {

        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbCSE;
    private javax.swing.JCheckBox cbECE;
    private javax.swing.JCheckBox cbISE;
    private javax.swing.JCheckBox cbMEC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextField txtCnameSearch;
    private javax.swing.JTextField txtMinPer;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
